# Generated by Django 4.2.7 on 2023-12-04 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_management', '0003_post_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='author',
        ),
    ]
