# Generated by Django 4.2.7 on 2023-12-11 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group_management', '0001_initial'),
        ('post_management', '0004_rename_user_comment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='group_management.group'),
        ),
    ]
