# Generated by Django 5.0 on 2023-12-15 17:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_management', '0002_remove_group_moderators'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='moderators',
            field=models.ManyToManyField(related_name='moderated_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
